### Probando Hoja de trucos de Numpy 
##### Campo de aplicacion 
##### Utilizando la hoja de trucos de Numpy, pruebe cada uno de los códigos y muestre los resultados de cada sección

[Hoja de trucos de Numpy](https://uraccan1-my.sharepoint.com/personal/yesser_miranda_5fxt_d_uraccan_edu_ni/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fyesser%5Fmiranda%5F5fxt%5Fd%5Furaccan%5Fedu%5Fni%2FDocuments%2FDOCENCIA%2F2021%2FS2%2FFUNDAMENTOS%5FINTELIGENCIA%5FARTIFICIAL%2FLIBROS%2FNumpy%5FCheatSheet%2Epdf&parent=%2Fpersonal%2Fyesser%5Fmiranda%5F5fxt%5Fd%5Furaccan%5Fedu%5Fni%2FDocuments%2FDOCENCIA%2F2021%2FS2%2FFUNDAMENTOS%5FINTELIGENCIA%5FARTIFICIAL%2FLIBROS&originalPath=aHR0cHM6Ly91cmFjY2FuMS1teS5zaGFyZXBvaW50LmNvbS86YjovZy9wZXJzb25hbC95ZXNzZXJfbWlyYW5kYV81Znh0X2RfdXJhY2Nhbl9lZHVfbmkvRVdkVnZ4T2lOSFZOdUtYeE1DS3FzdW9CMlpjYnd6REpENndrTk5fWHRJR0hXUT9ydGltZT12Qk5aSXZKbjJVZw)



##### Creando Arrays y Initial Placheholders

In [4]:
 import numpy as np
a = np.array([1,2,3])
print(a)
 b = np.array([(1.5,2,3), (4,5,6)], dtype = float)
print(b)
c = np.array([[(1.5,2,3), (4,5,6)], [(3,2,1), (4,5,6)]],dtype = float)
print(c)

[1 2 3]
[[1.5 2.  3. ]
 [4.  5.  6. ]]
[[[1.5 2.  3. ]
  [4.  5.  6. ]]

 [[3.  2.  1. ]
  [4.  5.  6. ]]]


In [41]:
#Create an array of zeros
np.zeros((3,4)) 

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [42]:
#Create an array of ones
np.ones((2,3,4),dtype=np.int16) 

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [5]:
#Create an array of evenly
d = np.arange(10,25,5) 
print(d)

[10 15 20]


In [8]:
#Create an array of evenly
# spaced values (number of samples)
np.linspace(0,2,9) 

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [9]:
#Create a constant array  
e = np.full((2,2),7) 
print(e)

[[7 7]
 [7 7]]


In [10]:
#Create a 2X2 identity matrix
f = np.eye(2)
print(f)

[[1. 0.]
 [0. 1.]]


In [47]:
#Create an array with random values
np.random.random((2,2))

array([[0.3909913 , 0.17469623],
       [0.97482956, 0.75841279]])

In [48]:
#Create an empty array
np.empty((3,2)) 

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

##### Saving & Loading On Disk

In [49]:
np.save('my_array', a)
np.savez('array.npz', a, b)
np.load('my_array.npy')

array([1, 2, 3])

##### Saving & Loading Text Files

In [ ]:
 np.loadtxt("myfile.txt")
np.genfromtxt("my_file.csv", delimiter=',')
 np.savetxt("myarray.txt", a, delimiter=" ")

##### Data Types 

In [ ]:
 np.int64  #Signed 64-bit integer types
np.float32 #Standard double-precision floating point
 np.complex #Complex numbers represented by 128 floats
np.bool #Boolean type storing TRUE and FALSE values
 np.object #Python object type
np.string_ #Fixed-length string type
 np.unicode_ #Fixed-length unicode type

##### Inspecting Your Array

In [29]:
# Array dimensions
a.shape 

(3,)

In [30]:
#Length of array 
len(a)

3

In [31]:
#Number of array dimensions
b.ndim

2

In [32]:
#Number of array elements
e.size

4

In [33]:
#Data type of array elements
b.dtype

dtype('float64')

In [34]:
# Name of data type 
b.dtype.name 

'float64'

In [35]:
#Convert an array to a different type
b.astype(int) 

array([[1, 2, 3],
       [4, 5, 6]])

In [57]:
# Asking For Help
np.info(np.ndarray.dtype)

Data-type of the array's elements.

Parameters
----------
None

Returns
-------
d : numpy dtype object

See Also
--------
numpy.dtype

Examples
--------
>>> x
array([[0, 1],
       [2, 3]])
>>> x.dtype
dtype('int32')
>>> type(x.dtype)
<type 'numpy.dtype'>


#### Array Mathematics
##### Arithmetic Operations

In [12]:
#Subtraction
g = a - b 
print(g)

[[-0.5  0.   0. ]
 [-3.  -3.  -3. ]]


In [13]:
### Subtraction Addition
np.subtract(a,b)
b+a

array([[2.5, 4. , 6. ],
       [5. , 7. , 9. ]])

In [14]:
## Addition Division 
np.add(b,a) 
a / b 

array([[0.66666667, 1.        , 1.        ],
       [0.25      , 0.4       , 0.5       ]])

In [15]:
#Division Multiplication
np.divide(a,b) 
a * b 

array([[ 1.5,  4. ,  9. ],
       [ 4. , 10. , 18. ]])

In [17]:
#Multiplication
np.multiply(a,b)


array([[ 1.5,  4. ,  9. ],
       [ 4. , 10. , 18. ]])

In [18]:
#Exponentiation
np.exp(b)

array([[  4.48168907,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [19]:
#Square root
np.sqrt(b)

array([[1.22474487, 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [20]:
#Print sines of an array
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

In [21]:
#Element-wise cosine 
np.cos(b)

array([[ 0.0707372 , -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029]])

In [22]:
#Element-wise natural logarithm
np.log(a)

array([0.        , 0.69314718, 1.09861229])

##### Comparison 


In [25]:
#Element-wise comparison
a == b

array([[False,  True,  True],
       [False, False, False]])

In [26]:
#Element-wise comparison
a < 2 

array([ True, False, False])

In [27]:
#Array-wise comparison
np.array_equal(a, b) 

False

##### Aggregate Functions

In [28]:
#Array-wise sum
a.sum() 

6

In [29]:
#Array-wise minimum value
a.min()

1

In [30]:
#Maximum value of an array row
b.max(axis=0)

array([4., 5., 6.])

In [31]:
#Cumulative sum of the elements
b.cumsum(axis=1) 

array([[ 1.5,  3.5,  6.5],
       [ 4. ,  9. , 15. ]])

In [32]:
#Mean
a.mean() 

2.0

In [35]:
#Median
b.median()

In [37]:
#Correlation coefficient
 a.corrcoef()

In [40]:
#Standard deviation
 np.std(b) 

##### Copying Arrays


In [42]:
#Create a view of the array with the same data
h = a.view() 
print(h)

[1 2 3]


In [43]:
#Create a copy of the array
np.copy(a)

array([1, 2, 3])

In [45]:
#Create a deep copy of the array
h = a.copy()
print(h)

[1 2 3]


##### Sorting Arrays

In [47]:
#Sort an array
a.sort() 
print(a)

[1 2 3]


In [49]:
#Sort the elements of an array's axis
c.sort(axis=0) 
print(a)

[1 2 3]


### Subsetting, Slicing, Indexing

##### Subsetting

In [50]:
#Select the element at the 2nd index
a[2] 

3

In [51]:
#Select the element at row 1 column 2
b[1,2]

6.0

##### Slicing

In [54]:
#Select items at index 0 and 1
a[0:2]

array([1, 2])

In [55]:
#Select items at rows 0 and 1 in column 1
b[0:2,1]

array([2., 5.])

In [57]:
#Select all items at row 0
b[:1] 


array([[1.5, 2. , 3. ]])

In [58]:
#Reversed array a 
a[ : :-1]

array([3, 2, 1])

##### Boolean Indexing

In [59]:
#Select elements from a less than 2
a[a<2] 

array([1])

##### Fancy Indexing

In [60]:
#Select elements (1,0),(0,1),(1,2) and (0,0)
b[[1, 0, 1, 0],[0, 1, 2, 0]]

array([4. , 2. , 6. , 1.5])

In [61]:
#Select a subset of the matrix’s rows and columns 
b[[1, 0, 1, 0]][:,[0,1,2,0]]

array([[4. , 5. , 6. , 4. ],
       [1.5, 2. , 3. , 1.5],
       [4. , 5. , 6. , 4. ],
       [1.5, 2. , 3. , 1.5]])

### Array Manipulation

##### Transposing Array

In [ ]:
#Permute array dimensions
 i = np.transpose(b)
#Permute array dimensions
i.T

##### Changing Array Shape


In [66]:
#Flatten the array
b.ravel() 

array([1.5, 2. , 3. , 4. , 5. , 6. ])

In [69]:
#Reshape, but don’t change data
 g.reshape(3,-2) 
    

##### Adding/Removing Elements

In [71]:
# Return a new array with shape (2,6)
h.resize(2,6)
print(h)

[[1 2 3 0 0 0]
 [0 0 0 0 0 0]]


In [75]:
#Append items to an array
np.append(h,g) 

array([ 1. ,  2. ,  3. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,
        0. , -0.5,  0. ,  0. , -3. , -3. , -3. ])

In [76]:
#Insert items in an array
np.insert(a, 1, 5) 

array([1, 5, 2, 3])

In [77]:
#Delete items from an array
np.delete(a,[1]) 

array([1, 3])

##### Combining Arrays


In [78]:
#Concatenate arrays
np.concatenate((a,d),axis=0) 

array([ 1,  2,  3, 10, 15, 20])

In [79]:
#Stack arrays vertically (row-wise)
np.vstack((a,b)) 

array([[1. , 2. , 3. ],
       [1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [80]:
#Stack arrays vertically (row-wise)
np.r_[e,f] 

array([[7., 7.],
       [7., 7.],
       [1., 0.],
       [0., 1.]])

In [85]:
#Create stacked column-wise arrays
np.c_[a,d]

array([[ 1, 10],
       [ 2, 15],
       [ 3, 20]])

##### Splitting Arrays

In [86]:
#Split the array horizontally at the 3rd index 
np.hsplit(a,3) 

[array([1]), array([2]), array([3])]

In [87]:
#Split the array vertically at the 2nd index
np.vsplit(c,2) 

[array([[[1.5, 2. , 1. ],
         [4. , 5. , 6. ]]]), array([[[3., 2., 3.],
         [4., 5., 6.]]])]